FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV TZ=America/Fortaleza
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies and Python 3
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libgtk2.0-dev \
    libpq-dev \
    gcc \
    git \
    cmake \
    unzip \
    wget \
    python3 \
    python3-dev \
    python3-pip

WORKDIR /home/age-emotion-detector
COPY ./lib/sort/sort.py ./lib/sort/sort.py

# Compile DLIB
RUN git clone https://github.com/davisking/dlib.git && \
    cd dlib && \
    mkdir build && \
    cd build && \
    cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1 && \
    cmake --build . && \
    cd .. && \
    python3 setup.py install

# Copy the face detector model file
WORKDIR /home/age-emotion-detector/resources
COPY age_deploy.prototxt age_deploy.prototxt
COPY age_net.caffemodel age_net.caffemodel
COPY dlib_face_recognition_resnet_model_v1.dat dlib_face_recognition_resnet_model_v1.dat
COPY emotionModel.hdf5 emotionModel.hdf5
COPY opencv_face_detector_uint8.pb opencv_face_detector_uint8.pb
COPY opencv_face_detector.pbtxt opencv_face_detector.pbtxt
COPY shape_predictor_68_face_landmarks.dat shape_predictor_68_face_landmarks.dat

WORKDIR /home/age-emotion-detector
# Install project requirements
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy the application code
COPY . .

# Run service
CMD ["python3", "main.py"]
