FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV TZ=America/Fortaleza
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies and Python 3
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libgtk2.0-dev \
    libpq-dev \
    gcc \
    git \
    cmake \
    unzip \
    wget \
    python3 \
    python3-dev \
    python3-pip

WORKDIR /home/age-emotion-detector
COPY ./lib/sort/sort.py ./lib/sort/sort.py
COPY ./lib/facial_emotions/facial_emotions.py ./lib/facial_emotions/facial_emotions.py

# Compile DLIB
RUN git clone https://github.com/davisking/dlib.git && \
    cd dlib && \
    mkdir build && \
    cd build && \
    cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1 && \
    cmake --build . && \
    cd .. && \
    python3 setup.py install

# Copy the face detector model file
WORKDIR /home/age-emotion-detector/resources

COPY ./resources/yolov8n-face.pt /home/age-emotion-detector/resources/yolov8n-face.pt
COPY ./resources/age_net.caffemodel /home/age-emotion-detector/resources/age_net.caffemodel
COPY ./resources/age_deploy.prototxt /home/age-emotion-detector/resources/age_deploy.prototxt
COPY ./resources/shape_predictor_68_face_landmarks.dat /home/age-emotion-detector/resources/shape_predictor_68_face_landmarks.dat
COPY ./resources/dlib_face_recognition_resnet_model_v1.dat /home/age-emotion-detector/resources/dlib_face_recognition_resnet_model_v1.dat

WORKDIR /home/age-emotion-detector

COPY pdf_report.py pdf_report.py

# Install project requirements
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy the application code
COPY . .

# Run service
CMD ["python3", "main.py"]
